# Generated by Django 5.0.2 on 2024-05-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0011_merge_20240508_1902'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='courses',
            field=models.ManyToManyField(related_name='videos', to='institution.course'),
        ),
    ]
