# Generated by Django 5.0.2 on 2024-05-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0011_merge_20240508_1902'),
        ('video', '0002_video_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subjects',
            field=models.ManyToManyField(related_name='videos', to='institution.subject'),
        ),
    ]
