# Generated by Django 5.0.2 on 2024-02-17 05:58

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=32, unique=True)),
                ("datetime_created", models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
        ),
    ]
