# Generated by Django 5.0.2 on 2024-03-06 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_program_users'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('name', 'institution')},
        ),
    ]
