# Generated by Django 5.0.2 on 2024-03-06 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_alter_program_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'program')},
        ),
    ]
