# Generated by Django 5.0.2 on 2024-04-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_subject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
