# Generated by Django 5.0.2 on 2024-04-17 17:22

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_alter_course_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('title', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='institution.course')),
            ],
        ),
    ]
