# Generated by Django 5.0.2 on 2024-04-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_alter_subject_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
    ]
