# Generated by Django 5.0.2 on 2024-04-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_announcement'),
        ('institution', '0007_course_users'),
    ]

    operations = [
    ]
