# Generated by Django 5.0.2 on 2024-04-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_remove_subject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
