# Generated by Django 3.2.23 on 2024-04-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_course_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='users',
        ),
    ]
