# Generated by Django 5.0.2 on 2024-04-24 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_alter_course_unique_together'),
        ('institution', '0008_subject_description'),
    ]

    operations = [
    ]
