# Generated by Django 5.0.2 on 2024-04-24 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_course_users'),
        ('institution', '0009_merge_20240423_2038'),
    ]

    operations = [
    ]
