# Generated by Django 5.0.2 on 2024-05-21 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0008_merge_0007_announcement_0007_course_users'),
        ('institution', '0009_course_users'),
        ('institution', '0010_merge_0007_course_users_0009_merge_20240423_2038'),
    ]

    operations = [
    ]
