# Generated by Django 5.1.15 on 2026-03-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0011_merge_20240508_1902'),
        ('institution', '0011_merge_20240521_1819'),
    ]

    operations = [
    ]
