# Generated by Django 5.1.15 on 2026-03-17 07:56

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0012_merge_20260317_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='password',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='datetime_created',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now()),
        ),
    ]
