# Generated by Django 5.1.15 on 2026-03-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0013_course_password_alter_announcement_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
